services:
  duro:
    build:
      context: .
    container_name: duro-core
    command: npm run start
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
  db:
    image: "mongo"
    volumes:
       - data-vol:/data/db
    ports:
      - 27017:27017
volumes:
  data-vol:
